name: NoiseMeter
options:
  bundleIdPrefix: com.noisemeter
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"

settings:
  base:
    DEVELOPMENT_TEAM: "BAMVK6LBVP"
    SWIFT_VERSION: "5.9"

targets:
  NoiseMeter:
    type: application
    platform: iOS
    sources:
      - NoiseMeter/Sources
      - NoiseMeter/Assets.xcassets
    settings:
      base:
        INFOPLIST_FILE: NoiseMeter/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.noisemeter.app
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: false
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - target: NoiseMeterWidgetExtension
        embed: true

  NoiseMeterWidgetExtension:
    type: app-extension
    platform: iOS
    product: NoiseMeterWidgetExtension
    sources:
      - path: NoiseMeterWidget
        excludes:
          - SharedData.swift
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.noisemeter.app.widget
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        CODE_SIGN_STYLE: Automatic
        INFOPLIST_FILE: NoiseMeterWidget/Info.plist
        GENERATE_INFOPLIST_FILE: false
        SKIP_INSTALL: true
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks"

  NoiseMeterUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - NoiseMeterUITests
    dependencies:
      - target: NoiseMeter
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.noisemeter.app.uitests
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: true
